### ISSUE TITLE
Adding search box on top of profile page for admins.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedCrew#16]

**Comment by halvors** [comment]
A nice thing would be to fetch the user's profile using JSON. So that you could dynamically just type the users name and it would present the user real time :dancers:

**Comment by petterroea** [comment]
Yeah. User pages have a lot of dependencies though. Is a possibility!

I can have a look at it, because there is some seatmap rendering involved

**Comment by petterroea** [comment]
We might want to make warbo make a "loading gif" to show while fetching data

**Comment by halvors** [comment]
A general available search box should be sufficent, then this is obsolete i think.

**Comment by halvors** [comment]
Postponing this, with the new design this may be obsolete.

**Comment by halvors** [comment]
Closing, can use normal search function.
