### ISSUE TITLE
If you don't have permissions, the seatmap overlaps the avatar

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedCrew#23]

**Comment by halvors** [comment]
Hmm what permissions are we talking about here? Cause...

![](http://i.imgur.com/gXrGh6N.jpg)

**Comment by halvors** [comment]
Hmm. This is a priority. May you take a look at this @petterroea. A quick look thru the code and i'm almost sure that this is not caused by missing permission. Have to be som seatmap css stuff.

**Comment by halvors** [comment]
@petterroea Are you working on this?

**Comment by petterroea** [comment]
Compo manager is top priority, but i will have a look at it soon(tm)

**Comment by halvors** [comment]
This is actually higher pri. Lot of chiefs aren't able to view user information.

**Comment by petterroea** [comment]
Yeah, i know

**Comment by halvors** [comment]
@petterroea Common, take a little time to look into this. It's critical.

**Comment by halvors** [comment]
This is top priority. @petterroea can you fix this during today?

**Comment by petterroea** [comment]
Fixing during after TG some time :)

But promise before next infected

**Comment by halvors** [comment]
@petterroea That's now! We really need this fix soon. Maybe the most annoying issue for users at the time being...

**Comment by petterroea** [comment]
Yeah, i see. I'l give it high pri and do it after test

**Comment by halvors** [comment]
@petterroea Excellent :+1:

**Comment by halvors** [comment]
@petterroea This is still high priority. Is this done?

**Comment by halvors** [comment]
This is no longer a problem, as the seatmap is moved to a subpage under profile.

**Comment by petterroea** [comment]
Sweet stuff
