### ISSUE TITLE
Recode the "Compo" manager to work with the new compo side

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedCrew#27]

**Comment by petterroea** [comment]
I will integrate this with the existing new compo system

**Comment by halvors** [comment]
If you need to fetch the old compo system, just look at earlier commits before the removal of the old code.

**Comment by petterroea** [comment]
No problem. 

About compo rule articles, what if we just assign an article to a compo? Cause i cant render the articles the same way at the compo page

**Comment by halvors** [comment]
I assume this is done?

**Comment by petterroea** [comment]
I think so
