### ISSUE TITLE
Improve avatar uploads

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedCrew#28]
Stuff that needs improvement:

 * More feedback to the user. Less subtle changes between stages
 * Auto-upload file once image is selected
 * Show cropping tool on image, mabe add a short paragraph on how you use it?

**Comment by petterroea** [comment]
I'l have a look at it

**Comment by halvors** [comment]
Is this done now?

**Comment by petterroea** [comment]
No, compo is pri. Most of these tickets are stuff i will have to do after infected.

**Comment by petterroea** [comment]
This is fixed?

**Comment by halvors** [comment]
No.

**Comment by petterroea** [comment]
Why is it closed, then?

**Comment by halvors** [comment]
#36

**Comment by petterroea** [comment]
Yeah, we need new design. Total revamp.

**Comment by halvors** [comment]
@petterroea This is done now right?

**Comment by petterroea** [comment]
Yes.
