### ISSUE TITLE
We're still using old form action call in edit-avatar.php

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedCrew#36]

**Comment by petterroea** [comment]
haaai

**Comment by halvors** [comment]
@petterroea Fikser du dette? Kanskje skrive om deler av avatar systemet? :)

**Comment by halvors** [comment]
@petterroea This is top priority, @Warbo- want this overhauled/rewritten.

**Comment by petterroea** [comment]
I know

**Comment by halvors** [comment]
@petterroea This is done now right?

**Comment by petterroea** [comment]
Yes
