### ISSUE TITLE
  Admins should be able to edit other crew's teams

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedCrew#48]
Right now, you need to change user to another crew's chief if you want to change stuff about that crew's teams(let's say a bug caused a member to be on another team then they should).

**Comment by halvors** [comment]
I see. I think we're gonna rewrite how this is handle anyway.

**Comment by halvors** [comment]
Implemented in commit df07c3336979846b6398cebb0928fb521df449a8
