### ISSUE TITLE
Notat på en bruker

### ISSUE THREAD

**Issue by Warbo-** [InfectedLan/InfectedCrew#50]
Kunne skrive notater på en bruker.
Brukeren skal selv ikke se notatene om seg selv, dette er bare no vi i ledelsen skal se.

Dette må bli en rettighet sånn at ikke alle kan se notatene som er skrevet om en person.

**Comment by halvors** [comment]
Working on it.

**Comment by halvors** [comment]
Implemented in commit e9afef4a14fdb5af28058440adb6a85b7e16a97f

**Comment by Warbo-** [comment]
Kan man få notate rett på brukern, uten at man trenger og trykke på en ekstra link.
Hele greia ser clean og pen ut. Så det jeg tenkte var om man bare kunne få den tekst boksen nederst på profilen til brukeren.

**Comment by Warbo-** [comment]
Når man trykker lagre på et notat blir man sendt til sin egen profil. Mer logisk om man da blir sendt til profilen til brukeren man har laget notat på.

**Comment by halvors** [comment]
Da er det fikset.

**Comment by halvors** [comment]
Skal vi lukke denne da?
