### ISSUE TITLE
Svømming ja/nei

### ISSUE THREAD

**Issue by Warbo-** [InfectedLan/InfectedCrew#51]
Kunne sette om en bruker skal på svømming eller ikke. 
Dette er ikke noe brukeren skal se selv, de skal heller ikke kunne stille på den.
Dette er noe de men rettigheten til og sette svømming bruker. vi må da også få en link under event som heter svømming. der vi får en liste med alle som skal på svømming og alle som ikke skal.

Gjør sånn som på rettigheter. sett dem i kategorier med hvilke crew dem er i.

Ser for meg at man på siden der man ser listen både kan adde og fjerne folk. og hvis du er inne på brukeren til en person kan du sette om han/hun skal på svømmin på selve brukeren også.

**Comment by halvors** [comment]
Denne er vel kanskje rettet mot @petterroea, eller er det inspirert av TG's nerdesvøm?

**Comment by petterroea** [comment]
Nei, tror ikke det. Er snakk om en feature på crewsiden hvor crew kan melde seg på crewsvømming. Er ikke det noe for deg?

**Comment by Warbo-** [comment]
Les det jeg skriver gutter, 

Dette er IKKE noe brukeren skal se selv, de skal heller IKKE kunne stille på den.

Dette er no ledelsen sette. så man gir rettigheten til de som måtte trenge det. dvs at chief og lagledere kan få det automatisk. og hvis det er noen uten om det gir man det som en rettighet.

**Comment by halvors** [comment]
@Warbo- Rettet mot security da? Trodde dette var pga @petterroea dro på svømming istedenfor å jobbe med jeg.

**Comment by halvors** [comment]
Altså sikter til svømmingen security pleier å ha.

**Comment by Warbo-** [comment]
Haha, nei det er ikke fordi Liam stikker av. Men bra forslag Halvor. brude lage et system der vi lett ser hvor ofte Liam gjør andre ting.

Men denne gangen var det for de som er på svømmingen med sec. Dette er forsovet åpent for alle, ikke bare sec.

**Comment by petterroea** [comment]
haha

**Comment by halvors** [comment]
Tenker vi kan legge dette til i user option funksjonen vi har sånn internt.

**Comment by halvors** [comment]
Implementert, ligger under profilen til folk for alle med "user.profile" rettighet.
