### ISSUE TITLE
Groups apparently sorted by group leader

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedCrew#54]
To reproduce: 
 * Log in as head for sec
 * Observe the list of groups in the team. What are they sorted by? Not ID. Changing the leader changes sorting(However, don't do this in production :P)

**Comment by halvors** [comment]
They are sorted by firstname and lastname.

**Comment by petterroea** [comment]
Talk to warbo about this. I thought this was the case, but he showed me otherwise

**Comment by halvors** [comment]
@petterroea Should we close the issue then?

**Comment by petterroea** [comment]
Not if it isn't fixed. Ask warbo for more information about the case

**Comment by halvors** [comment]
This is fixed, possibly when i rewrote the team management. And been approved by @Warbo-.

**Comment by petterroea** [comment]
Allright, np then
