### ISSUE TITLE
Checklist improvements

### ISSUE THREAD

**Issue by Warbo-** [InfectedLan/InfectedCrew#56]
Starter med det viktigste:

Kan ikke endre tidspunkt etter jeg har laget et punkt.
Når man trykker endre knappen går tiden til 00:00. selv om man ikke har endre noe på tid.

Få forskjellig farger på punktene i listen. Sånn at man lett greier og skille om punkte er delegert bort eller du har fått det av en annen. privat/stilling osv..

eksempler på farger:
Punker som er ferdig: Teskten blir grønn
Punkter som er over tiden: Tesksten blir rød
Private: Gul bakgrunn 
Stilling: Blå bakgrunn
Punkter du har fått delegert: En annen blåtone bakgrunn
Punkter du har delegert bort: lyslilla bakgrunn

punker du bare ser men ikke egentlig har: la stå med hvis bakgrunn. (dette har enda ikke kommet, men er en funksjen vi burde få så raskt som mulig. bare sånn at flere kan ha oversikt.)

Legge til at man kan vise punkte til flere, på samme måte som man delegerer et punkt. her burde man kunne sette flere personen. på samme måte som man inviterer folk til et lag på compo siden. bare her skal de jo da ikke trenge og godkjenne.

Legger ved noen bilder sånn at vi vet hva vi snakker om:
Edit delen:
![edit](https://copy.com/IJfCUIlaRmR00HD8)
Listen:
![listen](https://copy.com/zTLdvlJRglRI4iDl)

Hvis du selv er Ansvarlig på et punkt i listen kan ditt eget navn komme. sånn at det alltid er navn på et punk. Her kan vi endre så det bare står fornavn, så det ikke blir så lang. dette gjelde både når det er delegert bort og om man har fått ett punkt.

Som vi ser på bilde har vi noe som heter "Eier". Der Får vi som svar at den er "Din" eller "Delegert".
Det gir ikke helt mening for meg, siden jeg vet alle punktene er min, og jeg ser om jeg har delegert dem borte på høyre siden. (Da til lag eller en enkelt person). Burde vi endre den til at du fikk vite om punkte var privat eller på stilling?

Endre at man ikke får varsel en uke før, men 3 dager før. 

Endre teksten på "Deleger til lan" til "Deleger til lag-leder"

Har man bare delegert til et lag burde navne på den personen komme opp i listen på samme måte som det gjør når man har delegert til en enkelt person. Hvis dere ser Edit delen har jeg delegert "bord i multisalen" til sec. Jeg vet at Joakim er lagleder for sec. Så da burde jeg på samme måte som når jeg delegerte til marina se i listen min at det er Joakim som er Ansvarlig.

Når man trykker på Vis Detaljer, kunne man fått opp at bare detaljene på det punkte kom. ikke alle sammen.

På listen, kan man få alle ting til og bli venstre stilt. Sånn som nå er overskriftene litt rart plasert med tanke på hva som står under. Legger da mest merketil "Oppgave" og "Ansvarlig". Og om man kunne fått noe mer margin mellom dem. tenker kanskje 5px til mellom. Sånn at ikke Oppgaver står helt inntil Tidspunkt. Og vis detaljer helt inntil de som er ansvarlig.

**Comment by halvors** [comment]
> Kan ikke endre tidspunkt etter jeg har laget et punkt.
Når man trykker endre knappen går tiden til 00:00. selv om man ikke har endre noe på tid.

**Comment by halvors** [comment]
Legge til "watchlist" så andre brukere kan se andres gjøremål.

**Comment by halvors** [comment]
Watchlist funksjonen er nå ferdig og klar til bruk.

**Comment by halvors** [comment]
This is fully implemented.
