### ISSUE TITLE
Stop the checklist from posting all forms

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedCrew#61]
When one thing is checked, only submit that change.

**Comment by halvors** [comment]
Any progress on this?

**Comment by petterroea** [comment]
Next thing on the list!

I had a look at it today at school. I could not make new tasks(however, i got `result:true` from the json requests), and last crew's statuses were still here. We shouldn't export if an item is checked or not to the next event.

**Comment by petterroea** [comment]
Ayyy
